# Generated by Django 3.0.2 on 2020-01-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth',
            new_name='client',
        ),
    ]
