# Generated by Django 3.0.2 on 2020-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_auto_20200112_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
