# Generated by Django 3.0.2 on 2020-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_auto_20200112_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('tokenType', models.CharField(max_length=100, unique=True)),
                ('expires', models.DateTimeField()),
            ],
        ),
    ]
