# Generated by Django 3.0.2 on 2020-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stravaID', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_expires', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=200)),
            ],
        ),
    ]
