# Generated by Django 3.0.2 on 2020-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0005_runner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
