# Generated by Django 3.0.2 on 2020-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0006_auto_20200114_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='stravaID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
