# Generated by Django 5.2.1 on 2025-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0012_runner_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renamer',
        ),
        migrations.RenameField(
            model_name='runner',
            old_name='stravaID',
            new_name='strava_id',
        ),
        migrations.AlterField(
            model_name='runner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
