# Generated by Django 5.2.1 on 2025-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0013_delete_renamer_rename_stravaid_runner_strava_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=128)),
                ('event_time', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(choices=[('activity', 'Activity'), ('athlete', 'Athlete')], max_length=128)),
                ('owner_id', models.IntegerField()),
                ('subscription_id', models.IntegerField()),
                ('updates', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
