# Generated by Django 5.2.1 on 2025-06-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0014_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='event_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='strava.runner', to_field='strava_id'),
        ),
    ]
