# Generated by Django 5.2.1 on 2025-06-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0015_alter_update_event_time_alter_update_owner_id'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=50)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='strava.runner', to_field='strava_id')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='weather.weather')),
            ],
        ),
    ]
