# Generated by Django 5.2.2 on 2025-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0017_rename_update_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="object_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="subscription_id",
            field=models.BigIntegerField(),
        ),
    ]
