# Generated by Django 5.2.2 on 2025-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0018_alter_event_object_id_alter_event_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="strava_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
