# Generated by Django 5.2.2 on 2025-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0019_alter_activity_strava_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="event",
            name="aspect_type",
            field=models.CharField(
                choices=[("create", "create"), ("update", "update"), ("delete", "delete")], max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="object_type",
            field=models.CharField(choices=[("activity", "activity"), ("athlete", "athlete")], max_length=128),
        ),
    ]
