# Generated by Django 5.2.2 on 2025-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0020_rename_owner_id_event_owner_alter_event_aspect_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("avg_speed", models.FloatField()),
                ("max_speed", models.FloatField()),
            ],
        ),
    ]
