# Generated by Django 5.2.2 on 2025-08-21 19:54

from django.db import migrations
from django.core.management import call_command
from pathlib import Path


def load_fixture(apps, schema_editor):
    fixture_file_name = Path(__file__).parent / '0022_data.json'
    call_command('loaddata', fixture_file_name)

class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0021_animal"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
