# Generated by Django 5.2.2 on 2025-08-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0022_auto_20250821_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
