# Generated by Django 5.2.15 on 2026-07-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0023_alter_animal_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weather_report", models.BooleanField(default=True)),
                ("weather_emoji", models.BooleanField(default=True)),
                ("triathlon_score", models.BooleanField(default=True)),
                ("animal_comparison", models.BooleanField(default=True)),
                (
                    "runner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_settings",
                        to="strava.runner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "runner settings",
            },
        ),
    ]
