interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules ]]
path = "runtimeexceptions"
depends_on = []

[[modules ]]
path = "weather"
depends_on = []

[[modules ]]
path = "strava"
depends_on = ["weather"]
