# Generated by Django 3.0.2 on 2020-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websettings', '0002_auto_20180226_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
