# Generated by Django 3.0.2 on 2020-01-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websettings', '0003_auto_20200112_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='title',
            new_name='key',
        ),
    ]
