# Generated by Django 3.0.2 on 2020-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websettings', '0006_auto_20200113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
