# Generated by Django 3.0.4 on 2020-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websettings', '0007_auto_20200113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
