# Generated by Django 5.2.1 on 2025-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('detailed_status', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('temperature_feels_like', models.FloatField()),
                ('other_data', models.JSONField(default=dict)),
            ],
        ),
    ]
