---
name: "deploy"
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix known_hosts 
        run: |
          ssh-keygen -R ${{ secrets.SSH_HOST_URL }} || true

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: ${{ secrets.SSH_HOST_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
